apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: kubernetes-bootcamp
spec: 
  replicas: 2
  selector:
    matchLabels:
      app.k8s.io/name: kubernetes-bootcamp
  template: 
    metadata:
      labels:
        app.k8s.io/name: kubernetes-bootcamp
    spec: 
      containers:
        - name: kubernetes-bootcamp
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080




