apiVersion: v1 
kind: Service 
metadata: 
  name: kubernetes-bootcamp-service
spec: 
  selector:
    app.k8s.io/name: kubernetes-bootcamp
  ports:  
    - port: 8080
      targetPort: 8080
      nodePort: 30008
      protocol: TCP
  type: NodePort
