apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - port: 100
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
status:
  loadBalancer: {}
