apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: busybox
spec: 
  replicas: 3
  selector:
    matchLabels:
      app.k8s.io/name: busybox
  template: 
    metadata:
      labels:
        app.k8s.io/name: busybox
    spec: 
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sleep", "3600"]
          env:
            - name: name
              value: Mohamed Atef
            - name: age
              valueFrom:
                configMapKeyRef:
                  name: myage
                  key: my-nice-age 




