apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mariadb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: mariadb

  template: 
    metadata:
      labels:
        app.k8s.io/name: mariadb
    spec: 
      containers:
        - name: mariadb
          image: mariadb
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: username
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
            - name: MARIADB_DATABASE
              value: test
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password





